### ISSUE TITLE
支付宝支付网站安全性是否可完全有保障？

### ISSUE THREAD

**Issue by zsmynl** [fengli/alipay_python#8]
虽然也做了两年php，但是对站内支付这块安全性还是有所顾虑，您觉得这些顾虑是否多余，还有就是你对这一块的一个认识和看法，或者需要注意的点。

**Comment by fengli** [comment]
放心的用吧，那么大的公司在支持这个产品。没有什么好顾虑的。

**Comment by zsmynl** [comment]
ok~
